name: Git Builds

on:
  schedule:
    # At minute 17 past hour 8 and 14 (UTC) on every day-of-week from Monday through Thursday
    # https://crontab.guru
    - cron: '17 08,14 * * 1-5'
  workflow_dispatch:

env:
  ProjectFile: "src/NexusMods.App/NexusMods.App.csproj"

jobs:
  build-linux:
    uses: ./.github/workflows/build-linux-pupnet.yaml
    with:
      AppVersion: "0.0.1"
      # this is a bit of a hack, you can't use environment variables here
      # https://docs.github.com/en/actions/learn-github-actions/contexts#context-availability
      ProjectFile: ${{ needs.transformInputs.outputs.ProjectFile }}
      RetentionDays: 7

  build-windows:
    uses: ./.github/workflows/build-windows-pupnet.yaml
    with:
      AppVersion: "0.0.1"
      # this is a bit of a hack, you can't use environment variables here
      # https://docs.github.com/en/actions/learn-github-actions/contexts#context-availability
      ProjectFile: ${{ needs.transformInputs.outputs.ProjectFile }}
      RetentionDays: 7
